spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:17891/railway
    username: postgres
    password: FexBqkAHYPuJQNlBglvjHCrZqtECkCBI
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

demo:
  storage:
    type: local
    local:
      root-path: C:/storage/binary
