spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

demo:
  storage:
    type: local
    local:
      root-path: C:/storage/binary
