spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

backup:
  batch:
    interval: 3600000
  directory: ./hrbank05/backup

file:
  upload-dir: ./hrbank05/file/backup

demo:
  storage:
    type: local
    local:
      root-path: C:/storage/binary
