spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank_5
    password: hrbank_5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql

demo:
  storage:
    type: local
    local:
      root-path: C:/storage/binary